name: Update TTKRSS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # a cada 1h

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show git status (debug)
        run: |
          git status
          ls -la

      - name: Print subscriptions.csv with line numbers (debug)
        run: |
          echo "=== subscriptions.csv ==="
          nl -ba subscriptions.csv || echo "subscriptions.csv NOT FOUND"
          echo "========================="

      - name: Clean old outputs
        run: |
          mkdir -p feeds docs
          rm -f feeds/*.xml || true
          rm -f docs/*.xml || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (safe)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests beautifulsoup4

      - name: Run generator
        run: |
          if [ -f main.py ]; then python main.py; else echo "main.py not found"; fi
          if [ -f postprocessing.py ]; then python postprocessing.py || true; fi

      - name: Collect any XMLs into feeds/ and docs/
        run: |
          found=0
          while IFS= read -r -d '' f; do
            found=1
            echo "Found XML: $f"
            cp "$f" feeds/ || true
            cp "$f" docs/ || true
          done < <(find . -type f -name "*.xml" -print0)
          if [ "$found" -eq 0 ]; then echo "Nenhum XML gerado"; fi
          ls -la feeds || true
          ls -la docs || true

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "update feeds" || echo "No changes"
          git push
